### ISSUE TITLE
Android N Support

### ISSUE THREAD

**Issue by styppo** [mar-v-in/ArtHook#11]
Hooking fails on Android N with the following exception:

```
java.lang.RuntimeException: Clone not supported
    at de.larma.arthook.ArtMethod.clone(ArtMethod.java:296)
    at de.larma.arthook.ArtHook.hook(ArtHook.java:155)
    at de.larma.arthook.ArtHook.hook(ArtHook.java:141)
    ...
Caused by: java.lang.RuntimeException: Can't create new Method
    at de.larma.arthook.ArtMethod.newMethodM(ArtMethod.java:401)
    at de.larma.arthook.ArtMethod.newAssociatedMethodM(ArtMethod.java:365)
    at de.larma.arthook.ArtMethod.clone(ArtMethod.java:292)
    at de.larma.arthook.ArtHook.hook(ArtHook.java:155) 
    at de.larma.arthook.ArtHook.hook(ArtHook.java:141) 
    ...
Caused by: java.lang.SecurityException: Can not make a java.lang.reflect.Method constructor accessible
    at java.lang.reflect.AccessibleObject.setAccessible0(AccessibleObject.java:133)
    at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:89)
    at de.larma.arthook.ArtMethod.newMethodM(ArtMethod.java:386)
    at de.larma.arthook.ArtMethod.newAssociatedMethodM(ArtMethod.java:365) 
    at de.larma.arthook.ArtMethod.clone(ArtMethod.java:292) 
    at de.larma.arthook.ArtHook.hook(ArtHook.java:155) 
    at de.larma.arthook.ArtHook.hook(ArtHook.java:141)
    ...
```

Tested on AOSP 7.0, Build NRD90M.

**Comment by mar-v-in** [comment]
04b7ba1 was found to be working on armv8/6.0 and armv7a/7.0, other combinations are still to be tested...
